name: Build and test packages

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                node: [14.x, 16.x]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Setup node ${{ matrix.node }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}
            - uses: c-hive/gha-yarn-cache@v2
            - run: yarn install
            - run: yarn run format:check
            - run: yarn run build
            - run: yarn run test
