name: build

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ matrix.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            - name: Setup node 12
              uses: actions/setup-node@v2
              with:
                  node-version: 12.x
            - run: yarn install
              working-directory: fayr-ivp
            - run: yarn run format-check
              working-directory: fayr-ivp
            - run: yarn run build
              working-directory: fayr-ivp
            - run: yarn run test
              working-directory: fayr-ivp
