name: Build and test packages

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    matrix_prep:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}
        steps:
            # Required as the JSON input file needs to be read
            - uses: actions/checkout@v2
            # Adds `env.BRANCH_NAME`
            - uses: nelonoel/branch-name@v1.0.1
            - id: set-matrix
              uses: JoshuaTheMiller/conditional-build-matrix@main
              with:
                  inputFile: ".github/workflows/build-packages-matrix.json"
                  # https://jmespath.org/
                  filter: "[?runOnBranch==`${{ env.BRANCH_NAME }}` || runOnBranch==`always`].{os: os, node: node}"
    build:
        needs: matrix_prep
        strategy:
            matrix: ${{fromJson(needs.matrix_prep.outputs.matrix)}}
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Setup node ${{ matrix.node }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}
            - uses: c-hive/gha-yarn-cache@v2
            - run: yarn install --frozen-lockfile
            - run: yarn run format:check
            - run: yarn run build
            - run: yarn run test
