name: Deploy FAYR API

on:
    push:
        # TODO: Uncomment before merge
        # branches:
        # - main

jobs:
    deploy-fayr-api:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - uses: aws-actions/configure-aws-credentials@v1
              with:
                  # TODO: Create IAM role
                  # Docs: https://github.com/aws-actions/configure-aws-credentials
                  role-to-assume: arn:aws:iam::676057042583:role/fayr-github-actions-workflow-v1
                  aws-region: us-east-1
                  role-session-name: GitHubActions
            - working-directory: packages/fayr-api
              run: yarn install --frozen-lockfile
            - name: Serverless Authentication
              run: sls config credentials --provider aws --key ${{ env.AKIAZ22BDZ2LUDCZONUS }} --secret ${{ env.ttGiI4prymDA8ixjJryY4eh9OGKT4nSc7a8KWQNe }}
            - working-directory: packages/fayr-api
              run: yarn deploy
