name: Update licenses
on:
    push:
        branches:
            - main
        paths:
            - packages
jobs:
    create-licenses-pr:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Update licenses
                # In the long run, we should decide which of these tools we want to use. For now, save output of all to
                # be able to compare.
                run: |
                    yarn install
                    npx license-checker-rseidelsohn --excludePrivatePackages --json | sed -E 's/"(path|licenseFile)": "(.*)\/fayr_tv_live/"\1": "fayr_tv_live/g' > licensing/licenses.json
                    yarn licenses list | sed -e 's/└─ workspace-aggregator-.*\@/fayr-workspace@/g' | sed -e 's/Done in .*\.//g' > licensing/yarn-licenses.json
                    yarn licenses generate-disclaimer | sed -e 's/WORKSPACE AGGREGATOR .* PRODUCT/FAYR PRODUCT/g' > licensing/yarn-disclaimer.json
            -   name: Create Pull Request
                uses: peter-evans/create-pull-request@v3
                with:
                    commit-message: Update Licenses
                    title: Update Licenses
                    body: New licenses detected in dependencies, updated licenses.json
                    branch: update-licenses
